version: 1.2
workflows:
   - name: QuicKmer2
     subclass: WDL
     publish: True
     primaryDescriptorPath: /workflows/QuicKmer2.wdl
     testParameterFiles:
     authors:
       - name: Jeffrey Ng
     
