version: 1.2
workflows:
- name: QuicKmer2
  subclass: wdl
  primaryDescriptorPath: /workflows/QuicKmer2.wdl
  testParameterFiles:
- name: ACES
  subclass: wdl
  primaryDescriptorPath: /workflows/small_aces.wdl
  testParameterFiles:
